RAMA GALE
AMB2208

In [ ]:
import numpy as np
a=np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.ndim)

1


In [ ]:
print(a.shape)

(5,)


In [ ]:
print(a.size)

5


In [ ]:
print(a.nbytes)

40


In [ ]:
a=np.array([[0,1,2,3],[10,11,12,13,]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)


[[ 0  1  2  3]
 [10 11 12 13]]
(2, 4)
8
2


In [ ]:
import numpy as np
arr=np.array(2)
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.ndim)

2
()
1
<class 'numpy.ndarray'>
0


In [ ]:
import numpy as np
arr=np.array[2]
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.ndim)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
(5,)
5
<class 'numpy.ndarray'>
1


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5]])
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
9
<class 'numpy.ndarray'>
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("numberof dimension:",arr.ndim)

[[[[[1 2 3 4]]]]]
numberof dimension: 5


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
print(arr[2]+arr[3])

7


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[6,7,8,9]])
print('2nd element of 1st dimension',arr[0,1])

2nd element of 1st dimension 2


In [ ]:
import numpy as np
arr=np.array([[[1,2,3,4],[6,7,8,9],[3,4,56,78]]])
print(arr)
print('2nd element of 1st dimension',arr[0,1,2])

[[[ 1  2  3  4]
  [ 6  7  8  9]
  [ 3  4 56 78]]]
2nd element of 1st dimension 8


In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
print(sum)
dif=arr[3]-arr[2]
print(dif)
mul=arr[1]*arr[2]
print(mul)
div=arr[4]/arr[1]
print(div)

6
2
15
3.0


In [ ]:
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])
print(arr[-2:6])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]
[]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,1:4])
print()
print(arr[0:2,2])
print()
print(arr[0:2,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]

[3 8]

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newar=arr.reshape(2,3,2)
print(newar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newar=arr.resize(4*3)
print(newar)

None


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)
print(arr1@arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0 0]
 [0 0]]
[[19 22]
 [43 50]]


In [ ]:
con_arr=np.concatenate((arr1,arr2),axis=0)
print(con_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
con_arr=np.concatenate((arr1,arr2),axis=1)
print(con_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
tra_arr=arr.transpose()
print(tra_arr)
print()
fla_arr=arr.flatten()
print(fla_arr)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print("orginal array")
print(a)
print("checking for complex no")
print(np.iscomplex(a))
print("checking for real no")
print(np.isreal(a))
print("checking for scalar type")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

orginal array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking for complex no
[ True False False False False  True]
checking for real no
[False  True  True  True  True False]
checking for scalar type
True
False


In [ ]:

arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr=np.ones((2,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.empty((2,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#8/2/2026
import numpy as np
crop_yi=np.array([[12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
   [15.1,14.3,12.4,10.4,11.5],
   [11.2,10.9,12.1,11.7,12.8]])
print("crop yield :")
print(crop_yi)
print(f'\nshape: {crop_yi.shape}')
print(f'\ndata type{crop_yi.dtype}')
print(f'totsl element:{crop_yi.size}')
print(f'number of dimension:{crop_yi.ndim}')

crop yield :
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.3 12.4 10.4 11.5]
 [11.2 10.9 12.1 11.7 12.8]]

shape: (4, 5)

data typefloat64
totsl element:20
number of dimension:2


In [ ]:
total=np.sum(crop_yi)
ave_farm=np.mean(crop_yi,axis=1)
ave_sea=np.mean(crop_yi,axis=0)
max=np.max(crop_yi)
min=np.min(crop_yi)
print(f'total tield{total}')
print(f'{ave_farm}')
print(f"{ave_sea}")
print(max)
print(min)

total tield247.8
[13.76 11.32 12.74 11.74]
[12.275 12.475 12.35  12.    12.85 ]
15.2
10.3


In [ ]:
#finding best performance
best_farm=np.argmax(ave_farm)
print("\nbest performing farm:farm",best_farm+1)
print("there average yield",round(ave_farm[best_farm],2),"tons")




best performing farm:farm 1
there average yield 13.76 tons


In [ ]:
farm=np.argmin()

In [ ]:
exceptional=crop_yi >15
print(exceptional)
print('\nexceptional yield (>15):')
print(crop_yi[exceptional])

[[False False False False  True]
 [False False False False False]
 [ True False False False False]
 [False False False False False]]

exceptional yield (>15):
[15.2 15.1]


In [ ]:
categ=np.where(crop_yi>)